Sample to demonstrate custom `MessageConverter` to handle converting …
SolaceSamples/solace-samples-spring pull request #10
Opened 2022-03-16 15:08 UTC by gvensan

Sample to demonstrate custom `MessageConverter` to handle converting null payloads to custom POJOs.

How to use:
- Run the cloud-stream-sink-null-payload-converter 
- Publish an empty message from TryMe with an empty payload on the topic 'sensor/temperature/fahrenheit', which will publish a message on the topic with a null payload
- See that the null message passes through the converter and is returned as an empty POJO

Hope this the expectation in terms of sample for supporting custom message converter.

2022-03-21 19:11 UTC, Mrc0113 requested changes
Please see individual comments in this review.

2022-03-21 19:11 UTC, Mrc0113 commented on cloud-stream-sink-null-payload-converter/pom.xml
> +		<solace-spring-cloud-bom.version>2.3.0</solace-spring-cloud-bom.version>
please update with latest versions as Jeff requested in the JIRA.

2022-03-21 19:11 UTC, Mrc0113 commented on cloud-stream-sink-null-payload-converter/pom.xml
> +		<solace-spring-cloud-bom.version>2.3.0</solace-spring-cloud-bom.version>
bonus to also update the versions of the other Spring Cloud Stream samples in this repo and make sure they still run (it should "just work" ;) )

2022-03-21 19:11 UTC, Mrc0113 commented on cloud-stream-sink-null-payload-converter/src/main/java/com/solace/samples/spring/scs/TemperatureSink.java
> +    @Bean
add a comment that says something along the lines of

> if the payload is null, then the "solace_scst_nullPayload" message header will be set to true. Because the Spring framework does not allow for a message to have a null payload we need to add a custom message converter to handle that scenario.

2022-03-21 19:11 UTC, Mrc0113 commented on cloud-stream-sink-null-payload-converter/src/test/java/com/solace/samples/spring/scs/TemperatureSinkTest.java
> +		channel.send(MessageBuilder.withPayload(new SensorReading("test", 50, BaseUnit.FAHRENHEIT)).build());
Testing this would be interesting since Spring won't let us send a msg with a null payload. so what I would recommend here is to test manually that it works, delete this file and throw a comment in the main java class with a command they could use to test this via curl or sdkperf....or if you can use try-me just state how to do that :)

2022-03-23 04:25 UTC, gvensan commented on cloud-stream-sink-null-payload-converter/src/main/java/com/solace/samples/spring/scs/TemperatureSink.java
> +    @Bean
Done!

2022-03-23 04:26 UTC, gvensan commented on cloud-stream-sink-null-payload-converter/src/test/java/com/solace/samples/spring/scs/TemperatureSinkTest.java
> +		channel.send(MessageBuilder.withPayload(new SensorReading("test", 50, BaseUnit.FAHRENHEIT)).build());
Added a comment with approaches to generate  null payload events.

2022-03-23 16:48 UTC, Mrc0113 approved these changes

2022-03-23 16:49 UTC, merged